// <auto-generated />
namespace identity1.Common.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addimage3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addimage3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806141439360_add image3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
