// <auto-generated />
namespace identity1.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021631347_update order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
