// <auto-generated />
namespace identity1.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changeorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201806031238043_Changeorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
