// <auto-generated />
namespace identity1.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_relation_between_prod_and_charak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_relation_between_prod_and_charak));
        
        string IMigrationMetadata.Id
        {
            get { return "201806041642412_added_relation_between_prod_and_charak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
